language: node_js

node_js:
  - 'stable'

before_install:
  - "npm install http-server"
  - "chmod +x start_server.sh"
  - "./start_server.sh"
  - "cd tools"
  - "npm install --save-dev mocha chai should valid-url colors fs lodash colors puppeteer"

script: npm test
